### ISSUE TITLE
Malfunction of action module infoblox.nios_modules.nios_ptr_record

### ISSUE THREAD

**Issue by velotiger** [infobloxopen/infoblox-ansible#111]
#  Error when creating a new PTR RR

## Example Task

Remark: `status` is set in outer task. (Outer task calls dedicated files for A-, Name-, Host-, Ptr-Record depending on variable `rr.type`.)

```
# File: ptr.yaml
---
- name: "Set Ptr-Record: {{ rr.address }}, {{ rr.name }}, {{ status }}"
  infoblox.nios_modules.nios_ptr_record:
    comment: "{{ rr.comment | default('created by Ansible Role nios_rr-set') }}"
    ipv4: "{{ rr.address }}"
    ptrdname: "{{ rr.name }}"
    view: "{{ rr.view | default(VIEW) }}"
    state: "{{status }}"
  when:
  - rr.name is defined
  - rr.address is defined
...
  ```

### Variables

```
rr:
  name: testhost.example.domain
  address: 10.1.2.3
  type: ptr
  state: "{{ MY_STATE | default('present') }}"
VIEW: 'test_view'
```

## Expected Result

Create PTR RR «3.2.1.10.in-addr.arpa» → «testhost.example.domain».

## Error message

```
The full traceback is:
  File "/tmp/ansible_infoblox.nios_modules.nios_ptr_record_payload__31vjbm0/ansible_infoblox.nios_modules.nios_ptr_record_payload.zip/ansible_collections/infoblox/nios_modules/plugins/module_utils/api.py", line 209, in _invoke_method
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/infoblox_client/connector.py", line 50, in callee
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/infoblox_client/connector.py", line 383, in create_object
    raise exception(
fatal: [targethost.example.domain]: FAILED! => changed=false 
  code: Client.Ibap.Data.Conflict
  invocation:
    module_args:
      comment: created by Ansible Role nios_rr-set
      extattrs: null
      ipv4: 10.1.2.3
      ipv4addr: 10.1.2.3
      ipv6addr: null
      name: null
      provider:
        host: 10.0.0.1
        http_pool_connections: 10
        http_pool_maxsize: 10
        http_request_timeout: 8
        max_results: 100
        max_retries: 3
        password: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
        silent_ssl_warnings: false
        username: nios_admin
        validate_certs: true
        wapi_version: '2.10'
      ptrdname: testhost.example.domain
      state: present
      ttl: null
      view: test_view
  msg: An invalid IP address or reverse zone was specified.
  operation: create_object
  type: AdmConDataError
```

## Enviroment

* ansible [core 2.12.3]
* python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
* jinja version = 2.11.3
* libyaml = True
* Debian 11.2
* infoblox-client 0.5.0
* infoblox.nios_modules 1.2.1 (wapi_version: '2.10')
* NIOS 8.4.7
