### ISSUE TITLE
Cannot delete networks

### ISSUE THREAD

**Issue by spinoshi** [infobloxopen/infoblox-ansible#135]
I cannot delete networks from Infoblox using: 
```
    - name: Remove 192.168.1.0/30
      infoblox.nios_modules.nios_network:
        network: 192.168.1.0/30
        state: absent
        provider: "{{nios_provider}}"
```
The tasks is executed successfully ([OK]) but no actual change is done in Infoblox.
