### ISSUE TITLE
a_record cannot be removed without ipv4addr

### ISSUE THREAD

**Issue by ghost** [infobloxopen/infoblox-ansible#138]
I want to remove an A record. I don't care what the address on it is, I just want the record(s) gone. 

```yaml
- name:        remove A
  delegate_to: localhost
  infoblox.nios_modules.nios_a_record:
    provider: "{{ nios_provider }}"
    name:     anexample.com
    state:    absent
```
throws `FAILED! => {"changed": false, "msg": "missing required arguments: ipv4addr"}`.
