### ISSUE TITLE
state: absent fails if item is already absent

### ISSUE THREAD

**Issue by ghost** [infobloxopen/infoblox-ansible#139]
Using `nios_a_record` with `state: absent`, if the record does not exist, the module fails.
```yaml
hosts: all
tasks:
  - name:        remove A
    delegate_to: localhost
    infoblox.nios_modules.nios_a_record:
      provider: "{{ nios_provider }}"
      name:     "{{ item.name }}"
      ipv4addr: "{{ item.addr }}"
      state:    absent
    with_items:
      - name: xyz.com
        addr: 127.0.0.1
```
ansible-playbook -i xyz-dev1,xyz-dev2, play.yaml
```
changed: [xyz-dev1 -> localhost] => (item={'name': 'xyz.com', 'addr': '127.0.0.1'})
failed: [xyz-dev2 -> localhost] (item={'name': 'xyz.com', 'addr': '127.0.0.1'}) => {"ansible_loop_var": "item", "changed": false, "code": "Client.Ibap.Data.NotFound", "item": {"addr": "127.0.0.1", "name": "xyz.com"}, "msg": "Reference record:a/ZA5zLm17bmRfMAAuX2RlZlP1bHQuYQ9tLmVyY384LGRldi1yZXBvLnBvcL8ncmVzLDEwLjE1LjMuMTI1:xyz.com/default not found", "operation": "delete_object", "type": "AdmConDataNotFoundError"}
```
