### ISSUE TITLE
Error "Can not find requested number of networks" using nios_next_network lookup

### ISSUE THREAD

**Issue by miroslavkohutik** [infobloxopen/infoblox-ansible#156]
Infoblox returns an error: `Can not find requested number of networks` when trying to look up the next available network.
My playbook:
```
- hosts: localhost
  vars:
    nios_provider:
      host: 10.0.0.1
      username: user
      password: password
      wapi_version: 2.11.1
  tasks:
    - name: Create subnet
      infoblox.nios_modules.nios_network:
        provider: "{{ nios_provider }}"
        network: "{{ lookup('nios_next_network', '192.168.0.0/24', cidr=28, num=1, provider=nios_provider ) }}"
```

The full error message:
```
infoblox_client.exceptions.InfobloxFuncException: Error occurred during function's 'next_available_network' call: ref networkcontainer/ZG5zLm5ldHdvcmtfY29udGFpbmVyJDE5Mi4xNjguMC4wLzI0LzE:192.168.0.0/24/ipam: b'{ "Error": "AdmConDataError: None (IBDataError: IB.Data:Can not find requested number of networks)", \n  "code": "Client.Ibap.Data", \n  "text": "Can not find requested number of networks"\n}' [code 400]
````
