### ISSUE TITLE
Cannot inherit EAs from parent network while creating a host record

### ISSUE THREAD

**Issue by nikhilsharma343** [infobloxopen/infoblox-ansible#174]
Hi, 

Is there a way we can inherit EAs from parent network while creating a host record. I tried use_for_ea_inheritance: true but getting this error, was under impression NIOS inheriting the infoblox-client python module methods?

- name: Create Host Record
      nios_host_record:
        name: "{{ user_fqdn }}"
        ipv4addrs:
          - ipv4addr: "{{ user_ip }}"
          - use_for_ea_inheritance: true
        state: present
        provider:
          host: "{{ infoblox_server }}"
          username: "{{ infoblox_user }}"
          password: "{{ infoblox_pass }}"

**Comment by robertattenberger** [comment]
Hello,

I have got basically the same problem, but I use minimal different task-call and get a different error. The result that I cannot inherit EAs from parent network while creating a host record is also the same.

My task-call is the following:

```
- name: create DNS-host-record
  infoblox.nios_modules.nios_host_record:
    ipv4addrs:
      - ipv4addr: "{{ ip }}"
        use_for_ea_inheritance: true
    name: "{{ fqdn }}"
    provider:
      host: "{{ infoblox_fqdn }}"
      password: "{{ infoblox_password }}"
      username: "{{ infoblox_username }}"
    state: present
delegate_to: localhost
```

So I leave the "-" ahead of "use_for_ea_inheritance" away.
My error message is 'Unsupported parameters for (infoblox.nios_modules.nios_host_record) module: ipv4addrs.use_for_ea_inheritance. Supported parameters include: comment, view (dns_view), configure_for_dns (dns), aliases, state, extattrs, ipv4addrs (ipv4), provider, ipv6addrs (ipv6), ttl, name.'

I was able to fix that problem by doing the following adaption in collections/ansible_collections/infoblox/nios_modules/plugins/modules/nios_host_record.py

```
@@ -328,7 +328,8 @@ def main():
         configure_for_dhcp=dict(type='bool', required=False, aliases=['dhcp']),
         mac=dict(required=False),
         add=dict(type='bool', required=False),
-        remove=dict(type='bool', required=False)
+        remove=dict(type='bool', required=False),
+        use_for_ea_inheritance=dict(type='bool', required=False)
     )
     ipv6addr_spec = dict(
```

It would be great, if that or a similar adaption could be done in the official collection. This would affect that everyone could use it and we can upgrade the collection without needing to mention about that adaption.
