### ISSUE TITLE
clean warnings [WARNING]: Both option ipaddr and its alias ipaddr are set.

### ISSUE THREAD

**Issue by freedge** [infobloxopen/infoblox-ansible#20]
Using this task:

```
  - name: configure ipv4 dhcp fixed address based on existing lease
    nios_fixed_address:
      name: "{{ilo}}"
      ipaddr: "{{ lease.address }}"
      mac: "{{ lease.hardware }}"
      network: "{{lease.network }}"
      network_view: "{{lease.network_view}}"
      comment: iLO for {{ inventory_hostname }}
      state: present
      provider: "{{ nios_provider }}"
      extattrs:
        Project: myproject
        Editor: "{{nios_provider.username }}"
    delegate_to: localhost
```

the task seems to run successfully, but 4 warnings are logged (reproduced [here](https://dev.azure.com/freedge/freedge/_build/results?buildId=348&view=logs&j=1ebc38c8-fade-5a89-24da-f796855a97f6&t=7e545587-1914-5048-c05b-92ed6ea139f6&l=281))
```
[WARNING]: Both option ipaddr and its alias ipaddr are set.
[WARNING]: Both option mac and its alias mac are set.
[WARNING]: Both option network and its alias network are set.
[WARNING]: Both option network_view and its alias network_view are set.
```

I don't think I am providing these options twice. Is it possible to remove this warning, or can the warning indicate more clearly what is wrong?

Thanks
