### ISSUE TITLE
[RFE] - Add support for DNS view in DTC LBDN module

### ISSUE THREAD

**Issue by petj06** [infobloxopen/infoblox-ansible#217]
In my grid, I have multiple DNS views: Internal, External, and some others that are no longer used. Consider a domain name test.org (as an example) that exists in both Internal and External views. When I use the DTC LBDN module and specify a zone, pattern, and record type, after the playbook runs, the zone's **External** view is what is associated with the LBDN object. Is there a way to associate this with the internal view, or add support for the DNS view that other modules support (and require), such as the CNAME, A, and TXT record modules?

**Comment by JkhatriInfobox** [comment]
This is now supported as of v1.10.0 via #298, @petj06. The auth_zones parameter accepts both a plain FQDN string and a {fqdn, view} dict, so you can pin a zone to a specific DNS view:

```
- name: Configure a DTC LBDN with zones from different views
  infoblox.nios_modules.nios_dtc_lbdn:
    name: web.ansible.com
    lb_method: ROUND_ROBIN
    auth_zones:
      - example.com                        # First matching zone in any view
      - {"fqdn": "test.com", "view": "default"}  # Explicitly from default view
      - {"fqdn": "demo.com", "view": "custom"}   # From custom view
    patterns:
      - "*.example.com"
      - "*.test.com"
      - "*.demo.com"
    state: present
    provider: "{{ nios_provider }}"
```

When view is omitted, the first matching zone across all views is used. Closing as resolved.
