### ISSUE TITLE
Creating dns zone error

### ISSUE THREAD

**Issue by jcralbino** [infobloxopen/infoblox-ansible#236]
Hello
When running a single with a playbook to create a dns zone we have seen the following issue

1. The infoblox user is requested to have permissions to reboot the service , if a dns zone is create 

2. Even if restart if need flag is set to no, the creation of the dns zone is not occurring 

Can you please provide the following details
- What is the required permissions to allow a dns zone to be created ?
- what is the correct way to create a zone without having to restart the dns service

**Comment by sarya-infoblox** [comment]
Hello,

Thanks for reporting the issue.

**Required permissions to create a DNS zone:**

- Zone Read/Write permission
- Read/Write permission on the Grid member assigned to the zone (required when grid_primary, grid_secondaries, or ns_group is specified)

**Creating a zone without restarting the DNS service:**

Set restart_if_needed: false in the task. The zone will be created and the DNS service restart will remain pending until performed manually.

**Please note**: Grid member Read/Write permission is still required even when restart_if_needed: false is set, if a Grid member is attached to the zone.


Example playbook:

```yaml id="5gk1pz"
---
- name: Create DNS zone
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    nios_provider:
      host: "<grid-ip>"
      username: "<username>"
      password: "<password>"

  tasks:
    - name: Create zone
      infoblox.nios_modules.nios_zone:
        name: "example.com"
        grid_primary:
          - name: "<grid-member-fqdn>"
        restart_if_needed: false
        state: present
        provider: "{{ nios_provider }}"
```

If the issue persists after validating the permissions mentioned above, please raise a new issue and share:

* The exact playbook being used
* Complete error message/output
* NIOS version
* `infoblox.nios_modules` version

This will help us investigate your specific environment further.

Thanks!
