### ISSUE TITLE
nios_a_record fails when using environment variables for provider data

### ISSUE THREAD

**Issue by murrahjm** [infobloxopen/infoblox-ansible#255]
Given the following sample code:

```yaml
infoblox.nios.nios_a_record:
  name: testrecord.domain.com
  view: default
  ipv4addr: 10.10.10.10
```

with the following environment variables set:

INFOBLOX_HOST
INFOBLOX_USERNAME
INFOBLOX_PASSWORD

the task fails with this error:

"ansible.module_utils.api.get_connector() argument after ** must be a mapping, not NoneType"

I think it's referencing this: https://github.com/infobloxopen/infoblox-ansible/blame/1c947713461d0869c7ef44261ad12a0389be9b99/plugins/module_utils/api.py#L244C44-L244C44
