### ISSUE TITLE
nios_host_record error when trying to change ip of host record

### ISSUE THREAD

**Issue by Akasurde** [infobloxopen/infoblox-ansible#62]
_From @martinberg on Aug 07, 2020 13:36_

##### SUMMARY
It doesn't seem to be possible to change the ip of a host record with nios_host_record. Ansible returns an error that "The record 'test.example.com' already exists"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nios_host_record

##### ANSIBLE VERSION
```
ansible 2.9.11
  config file = /home/user/temp/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.6/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 3.6.8 (default, Jun 11 2019, 15:15:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/user/temp/ansible/ansible.cfg) = ['/home/user/temp/ansible/hosts']
HOST_KEY_CHECKING(/home/user/temp/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
localhost: RHEL 7.7
Infoblox: 8.2.4

##### STEPS TO REPRODUCE
There is an existing host record in the "EXTERN" DNS view called 'testdomain.x.com' with IP-adress '1.1.1.99'

```
- name: DNS change host ip
  hosts: localhost
  connection: local
  vars:
    nios_provider:
      host: infoblox-host
      username: user
      password: passwd

    dns_revert_list:
      - {hostname: "testdomain.x.com", ip: "1.1.1.100", dnsview: "EXTERN"}

  tasks:
  - name: Change host record IP
    nios_host_record:
      name: "{{ item.hostname }}"
      ipv4:
        - address: "{{ item.ip }}"
      view: "{{ item.dnsview }}"
      state: present
      provider: "{{ nios_provider }}"
    with_items: "{{ dns_revert_list }}"
    tags:
    - site2ip
```

##### EXPECTED RESULTS
IP of host record to be changed

##### ACTUAL RESULTS
Error saying the record already exists. No change was made in the Infoblox environment.

```
failed: [localhost] (item={'hostname': 'testdomain.x.com', 'ip': '1.1.1.100', 'dnsview': 'EXTERN'}) => {"ansible_loop_var": "item", "changed": false, "code": "Client.Ibap.Data.Conflict", "item": {"dnsview": "EXTERN", "hostname": "testdomain.x.com", "ip": "1.1.1.100"}, "msg": "The record 'testdomain.x.com' already exists.", "operation": "create_object", "type": "AdmConDataError"}
```

_Copied from original issue: ansible/ansible#748_

**Comment by Akasurde** [comment]
_From @ansibullbot on Aug 07, 2020 13:38_

Files identified in the description:
* [`plugins/modules/net_tools/nios/nios_host_record.py`](https://github.com/ansible-collections/community.general/blob/master/plugins/modules/net_tools/nios/nios_host_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
_From @ansibullbot on Aug 07, 2020 13:38_

cc @NilashishC @Qalthos @danielmellado @ganeshrn @justjais @nerzhul @privateip @sganesh-infoblox @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
_From @russoz on May 19, 2021 21:42_

Hi there

The main development of the nios modules has moved over to https://github.com/infobloxopen/infoblox-ansible/

You should probably create the same issue there and close this one. The nios modules are set for deprecation in community.general on version 5.0.0 (spring 2022, still far away but nonetheless set).

Thanks for your contribution!

**Comment by badnetmask** [comment]
According to [this portion of the code](https://github.com/infobloxopen/infoblox-ansible/blob/master/ansible_collections/infoblox/nios_modules/plugins/modules/nios_host_record.py#L48), in order to modify the IP addresses you need to use the sub-options add and remove. Something like this (I haven't tested):
```
  - name: Change host record IP
    nios_host_record:
      name: "{{ item.hostname }}"
      ipv4:
        - address: "{{ item.old_ip }}"
          remove: true
        - address: "{{ item.new_ip }}"
          add: true
```
I have not tested this yet (unable to access my lab right now), so would you be able to try it yourself?
If that works, it might just need [an update in the documentation](https://github.com/infobloxopen/infoblox-ansible/blob/master/ansible_collections/infoblox/nios_modules/plugins/modules/nios_host_record.py#L205).

**Comment by badnetmask** [comment]
@martinberg -- can you please review the response above, and confirm if it fixes your problem?

**Comment by bdavis0656** [comment]
I can confirm that it does not work. It does not recognize add or remove as supported parameters.

{"changed": false, "msg": "Unsupported parameters for (nios_host_record) module: remove found in ipv4addrs. Supported parameters include: configure_for_dhcp, ipv4addr, mac"}

**Comment by badnetmask** [comment]
Sorry for the long radio silence.
For completeness, I went back to look at this issue and found out that the documentation is not well written in what regards to this particular operation.
It seems like in order to modify an IP address you have to first **add** the new, then **remove** the old, in two different actions.
I see how this can get a bit complicated, so I am leaving this comment for any possible future enhancements to this module.
```
- name: DNS change host ip
  hosts: localhost
  connection: local
  vars:
    nios_provider:
      host: infoblox-host
      username: admin
      password: infoblox

    host_list:
      - {hostname: "netmask-ansible-test.example.com", old_ip: "192.168.1.1", new_ip: "192.168.1.220"}

  tasks:
  - name: Create host record with old IP
    infoblox.nios_modules.nios_host_record:
      name: "{{ item.hostname }}"
      ipv4addrs:
        - address: "{{ item.old_ip }}"
      state: present
      provider: "{{ nios_provider }}"
    with_items: "{{ host_list }}"

  - name: Add new IP to host record
    infoblox.nios_modules.nios_host_record:
      name: "{{ item.hostname }}"
      ipv4addrs:
        - address: "{{ item.new_ip }}"
          add: true
      state: present
      provider: "{{ nios_provider }}"
    with_items: "{{ host_list }}"

  - name: Delete old IP from host record
    infoblox.nios_modules.nios_host_record:
      name: "{{ item.hostname }}"
      ipv4addrs:
        - address: "{{ item.old_ip }}"
          remove: true
      state: absent
      provider: "{{ nios_provider }}"
    with_items: "{{ host_list }}"
```
