### ISSUE TITLE
nios_a_record issue - Updated the name of a record, but name was not changed by a new name.

### ISSUE THREAD

**Issue by hong235** [infobloxopen/infoblox-ansible#90]

**Comment by JkhatriInfobox** [comment]
Thanks for the report!

We have investigated and tested this on the current master branch against a live NIOS grid. The A record rename is working as expected with no issues found.

**Test Environment: **
```
infoblox.nios_modules version: 1.9.0
ansible-core version: 2.21.0
NIOS version: 9.0.x (WAPI 2.14)
```
What we tested

`Pre-state: A record v7.testzone.com pointing to 1.1.11.2 exists in view testDnsView.`

Playbook task used:
```
- name: Update Nios A record
  infoblox.nios_modules.nios_a_record:
    name: { new_name: v7-new.testzone.com, old_name: v7.testzone.com }
    view: testDnsView
    ipv4: 1.1.11.2
    state: present
    provider: "{{ nios_provider }}"
```

Post-state: Only v7-new.testzone.com exists in NIOS. The old name v7.testzone.com is gone. 
The task reported changed: true.

**Conclusion: **

The rename functionality is working correctly on the latest version of the collection. This may have been a bug in an earlier version that has since been resolved. We recommend upgrading to infoblox.nios_modules >= 1.9.0 and retrying.

If you are still able to reproduce this with the latest version, please reopen the issue and include your full playbook, the collection version you are using, and the complete error output.

Closing this issue for now.
